# Generated by Django 5.2.11 on 2026-02-11 05:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('center_lng', models.FloatField(default=0)),
                ('center_lat', models.FloatField(default=0)),
                ('default_zoom', models.FloatField(default=13)),
                ('default_pitch', models.FloatField(default=0)),
                ('default_bearing', models.FloatField(default=0)),
                ('mapbox_style', models.CharField(blank=True, max_length=200)),
                ('background_color', models.CharField(default='#FFE9CF', max_length=9)),
                ('text_color', models.CharField(default='#434431', max_length=9)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='guides.destination')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('experience_type', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#000000', max_length=9)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('effort', models.CharField(blank=True, choices=[('easy', 'Easy'), ('gentle', 'Gentle'), ('fair', 'Fair'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=20)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('best_time', models.CharField(blank=True, max_length=100)),
                ('about', models.JSONField(blank=True, default=list)),
                ('what_you_get', models.JSONField(blank=True, default=list)),
                ('why_we_chose_this', models.TextField(blank=True)),
                ('golden_way', models.TextField(blank=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('spreadsheet_data', models.JSONField(blank=True, default=dict)),
                ('center_lng', models.FloatField(default=0)),
                ('center_lat', models.FloatField(default=0)),
                ('zoom', models.FloatField(default=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='guides.destination')),
                ('related_experiences', models.ManyToManyField(blank=True, to='guides.experience')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experience_images/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guides.experience')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('route', 'Route'), ('zone', 'Zone'), ('poi', 'Point of Interest')], max_length=10)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('zone', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('fill_opacity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('poi_type', models.CharField(blank=True, max_length=50)),
                ('folder', models.CharField(blank=True, max_length=200)),
                ('folder_category', models.CharField(blank=True, max_length=100)),
                ('kml_source', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_features', to='guides.destination')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_features', to='guides.experience')),
            ],
            options={
                'ordering': ['feature_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('tip', models.TextField(blank=True)),
                ('support_line', models.CharField(blank=True, max_length=300)),
                ('color', models.CharField(default='#000000', max_length=9)),
                ('illustration', models.ImageField(blank=True, upload_to='mood_illustrations/')),
                ('is_special', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='guides.destination')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('destination', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='guides.mood'),
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('place_type', models.CharField(blank=True, max_length=50)),
                ('primary_type', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_rating_count', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='guides.destination')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='guides.experience')),
            ],
            options={
                'ordering': ['-rating'],
                'unique_together': {('experience', 'google_place_id')},
            },
        ),
    ]
