# Generated by Django 5.2.11 on 2026-02-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('location', '0002_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='location.state'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_published', 'sort_order', 'name'], name='guides_dest_is_publ_d75a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['destination', 'is_published', 'sort_order'], name='guides_expe_destina_e7b549_idx'),
        ),
    ]
