# Generated by Django 5.2.11 on 2026-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_destination_state_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='bounds_ne_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='bounds_ne_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='bounds_sw_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='bounds_sw_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
