# Generated by Django 5.2.11 on 2026-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_add_destination_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='card_background',
            field=models.CharField(blank=True, help_text='CSS color for mood card background, e.g. rgba(61,122,104,0.25)', max_length=60),
        ),
    ]
