# Generated by Django 5.2.11 on 2026-02-17 17:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='department_photos/')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('schedule', models.JSONField(default=dict, help_text='Schedule JSON with timezone, default hours, and overrides')),
                ('is_ops', models.BooleanField(default=False, help_text='Ops departments never pause escalation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('last_run', models.DateTimeField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAILED', 'Failed')], max_length=10)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='experience_photos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='experience_covers/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_display', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('DINING', 'Dining'), ('SPA', 'Spa'), ('ACTIVITY', 'Activity'), ('TOUR', 'Tour'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=20)),
                ('timing', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('highlights', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='concierge.department')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='hotel_logos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='hotel_covers/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('room_number_pattern', models.CharField(default='^\\d{3,4}$', help_text='Regex for valid room numbers', max_length=100)),
                ('blocked_room_numbers', models.JSONField(default=list, help_text='Room numbers that are always rejected')),
                ('room_number_min', models.IntegerField(blank=True, null=True)),
                ('room_number_max', models.IntegerField(blank=True, null=True)),
                ('escalation_enabled', models.BooleanField(default=False)),
                ('escalation_fallback_channel', models.CharField(choices=[('NONE', 'None'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('EMAIL_SMS', 'Email + SMS')], default='NONE', max_length=10)),
                ('oncall_email', models.EmailField(blank=True, max_length=254)),
                ('oncall_phone', models.CharField(blank=True, max_length=20)),
                ('require_frontdesk_kiosk', models.BooleanField(default=True)),
                ('escalation_tier_minutes', models.JSONField(blank=True, help_text='Per-hotel override, e.g. [15, 30, 60]. Falls back to settings default.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for_hotels', to='concierge.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='concierge.hotel'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField(help_text='{ endpoint, keys: { p256dh, auth } } — no user_agent, no IP')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short non-sequential public identifier', max_length=20, unique=True)),
                ('placement', models.CharField(choices=[('LOBBY', 'Lobby'), ('ROOM', 'Room'), ('RESTAURANT', 'Restaurant'), ('SPA', 'Spa'), ('POOL', 'Pool'), ('BAR', 'Bar'), ('GYM', 'Gym'), ('GARDEN', 'Garden'), ('OTHER', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('qr_image', models.ImageField(upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='concierge.department')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='concierge.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='GuestStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_stays', to='concierge.hotel')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_stays', to='concierge.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('request_type', models.CharField(choices=[('BOOKING', 'Booking'), ('INQUIRY', 'Inquiry'), ('CUSTOM', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACKNOWLEDGED', 'Acknowledged'), ('CONFIRMED', 'Confirmed'), ('NOT_AVAILABLE', 'Not Available'), ('NO_SHOW', 'No Show'), ('ALREADY_BOOKED_OFFLINE', 'Already Booked Offline'), ('EXPIRED', 'Expired')], default='CREATED', max_length=25)),
                ('guest_notes', models.TextField(blank=True)),
                ('guest_date', models.DateField(blank=True, null=True)),
                ('guest_time', models.TimeField(blank=True, null=True)),
                ('guest_count', models.IntegerField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('confirmation_reason', models.CharField(blank=True, max_length=50)),
                ('after_hours', models.BooleanField(default=False)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='concierge.department')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='concierge.experience')),
                ('guest_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='concierge.gueststay')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='concierge.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('VIEWED', 'Viewed'), ('ACKNOWLEDGED', 'Acknowledged'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('NOTE_ADDED', 'Note Added'), ('EXPIRED', 'Expired')], max_length=20)),
                ('escalation_tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='concierge.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('ESCALATION', 'Escalation'), ('DAILY_DIGEST', 'Daily Digest'), ('SYSTEM', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='concierge.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='concierge.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hotel', 'slug')},
        ),
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_memberships', to='concierge.department')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='concierge.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], default='WHATSAPP', max_length=10)),
                ('gupshup_message_id', models.CharField(blank=True, max_length=100)),
                ('sms_fallback_sent', models.BooleanField(default=False)),
                ('wa_delivered', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='concierge.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'created_at'], name='concierge_o_phone_efb030_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gueststay',
            index=models.Index(fields=['hotel', 'room_number', 'created_at'], name='concierge_g_hotel_i_c823e7_idx'),
        ),
        migrations.AddIndex(
            model_name='gueststay',
            index=models.Index(fields=['guest', 'hotel'], name='concierge_g_guest_i_3323cc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['hotel', 'status', 'created_at'], name='concierge_s_hotel_i_1492ea_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['hotel', 'created_at'], name='concierge_s_hotel_i_15d7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['guest_stay', 'created_at'], name='concierge_s_guest_s_422a56_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['hotel', 'updated_at'], name='concierge_s_hotel_i_72013e_idx'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['request', 'action'], name='concierge_r_request_96eef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'ESCALATED')), fields=('request', 'escalation_tier'), name='unique_escalation_per_tier'),
        ),
        migrations.AddConstraint(
            model_name='requestactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'ESCALATED'), ('escalation_tier__isnull', False)), models.Q(('action', 'ESCALATED'), _negated=True), _connector='OR'), name='escalated_requires_tier'),
        ),
        migrations.AddConstraint(
            model_name='requestactivity',
            constraint=models.CheckConstraint(condition=models.Q(('action', 'ESCALATED'), models.Q(('claimed_at__isnull', True), ('notified_at__isnull', True)), _connector='OR'), name='claim_notify_only_for_escalated'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='concierge_n_user_id_ba5bae_idx'),
        ),
    ]
