# Generated by Django 5.2.11 on 2026-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='sms_fallback_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
