# Generated by Django 5.2.11 on 2026-02-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_experienceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='experience',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=12),
        ),
    ]
