# Generated by Django 5.2.11 on 2026-02-18 18:15

from django.db import migrations


def populate_status_from_is_active(apps, schema_editor):
    """Map existing is_active boolean to ContentStatus enum."""
    Department = apps.get_model('concierge', 'Department')
    Experience = apps.get_model('concierge', 'Experience')

    # Departments: is_active=True → PUBLISHED, False → UNPUBLISHED
    Department.objects.filter(is_active=True).update(
        status='PUBLISHED',
        published_at=models_now(),
    )
    Department.objects.filter(is_active=False).update(status='UNPUBLISHED')

    # Experiences: same pattern
    Experience.objects.filter(is_active=True).update(
        status='PUBLISHED',
        published_at=models_now(),
    )
    Experience.objects.filter(is_active=False).update(status='UNPUBLISHED')


def models_now():
    from django.utils import timezone
    return timezone.now()


def reverse_status_to_is_active(apps, schema_editor):
    """Reverse: sync is_active from status."""
    Department = apps.get_model('concierge', 'Department')
    Experience = apps.get_model('concierge', 'Experience')

    Department.objects.filter(status='PUBLISHED').update(is_active=True)
    Department.objects.exclude(status='PUBLISHED').update(is_active=False)

    Experience.objects.filter(status='PUBLISHED').update(is_active=True)
    Experience.objects.exclude(status='PUBLISHED').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0004_add_content_status_fields'),
    ]

    operations = [
        migrations.RunPython(
            populate_status_from_is_active,
            reverse_status_to_is_active,
        ),
    ]
