# Generated by Django 5.2.11 on 2026-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0005_populate_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='settings_configured',
            field=models.BooleanField(default=False, help_text='Set to True when admin first saves hotel settings'),
        ),
    ]
