# Generated by Django 5.2.11 on 2026-02-19 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0006_add_settings_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='accent_color',
            field=models.CharField(default='#b45309', help_text='Accent/CTA color (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #1a1a1a)', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='body_font',
            field=models.CharField(blank=True, default='', help_text='Google Font name for body text', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='hotel_favicons/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='heading_font',
            field=models.CharField(blank=True, default='', help_text='Google Font name for headings', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='hotel_og/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='primary_color',
            field=models.CharField(default='#1a1a1a', help_text='Primary brand color (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #1a1a1a)', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='privacy_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='secondary_color',
            field=models.CharField(default='#f5f5f4', help_text='Secondary brand color (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #1a1a1a)', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='terms_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='With country code, e.g. +919876543210', max_length=20),
        ),
    ]
