# Generated by Django 5.2.11 on 2026-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0007_add_hotel_branding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='body_font',
            field=models.CharField(blank=True, default='Brinnan', help_text='Font name for body text', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='heading_font',
            field=models.CharField(blank=True, default='BioRhyme', help_text='Font name for headings', max_length=100),
        ),
    ]
