# Generated by Django 5.2.11 on 2026-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0008_change_default_fonts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, upload_to='department_icons/'),
        ),
    ]
