# Generated by Django 5.2.11 on 2026-02-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0009_change_icon_to_imagefield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('department', 'slug')},
        ),
    ]
