# Generated by Django 5.2.11 on 2026-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0011_dedupe_stays_unique_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
