# Generated by Django 5.2.11 on 2026-02-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0012_add_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestactivity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('VIEWED', 'Viewed'), ('ACKNOWLEDGED', 'Acknowledged'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('NOTE_ADDED', 'Note Added'), ('OWNERSHIP_TAKEN', 'Ownership Taken'), ('EXPIRED', 'Expired')], max_length=20),
        ),
    ]
