# Generated by Django 5.2.11 on 2026-02-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0013_add_ownership_taken_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='For recurring events: which occurrence the guest selected', null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='event_photos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='event_covers/')),
                ('price_display', models.CharField(blank=True, max_length=100)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('DINING', 'Dining'), ('SPA', 'Spa'), ('ACTIVITY', 'Activity'), ('TOUR', 'Tour'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('auto_expire', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='For request routing. Null = hotel-wide (falls back to hotel.fallback_department)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='concierge.department')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='concierge.experience')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='concierge.hotel')),
            ],
            options={
                'ordering': ['display_order', 'event_start'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='concierge.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['hotel', 'status', 'is_featured', 'event_start'], name='concierge_e_hotel_i_e65eae_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['hotel', 'status', 'auto_expire', 'event_end'], name='concierge_e_hotel_i_d243c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('event_end__isnull', True), ('event_end__gte', models.F('event_start')), _connector='OR'), name='event_end_gte_start'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('hotel', 'slug')},
        ),
    ]
