# Generated by Django 5.2.11 on 2026-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0015_booking_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='deal_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='deal_price_display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_top_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_top_deal', 'deal_ends_at'], name='concierge_e_is_top__4e659c_idx'),
        ),
    ]
