# Generated by Django 5.2.11 on 2026-02-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0016_add_top_deal_fields_to_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_sections', to='concierge.hotel')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['hotel', 'display_order'], name='concierge_h_hotel_i_578d84_idx')],
            },
        ),
    ]
