# Generated by Django 5.2.11 on 2026-02-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0017_hotel_info_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='Welcome message paragraph(s)')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature highlight strings')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Email Template',
            },
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='placement',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('ROOM', 'Room'), ('RESTAURANT', 'Restaurant'), ('SPA', 'Spa'), ('POOL', 'Pool'), ('BAR', 'Bar'), ('GYM', 'Gym'), ('GARDEN', 'Garden'), ('BOOKING', 'Booking Email'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.UniqueConstraint(condition=models.Q(('placement', 'BOOKING')), fields=('hotel',), name='unique_booking_qr_per_hotel'),
        ),
        migrations.AddField(
            model_name='bookingemailtemplate',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_email_template', to='concierge.hotel'),
        ),
        migrations.AddField(
            model_name='bookingemailtemplate',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='Auto-created BOOKING QR code. Links to hotel landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.qrcode'),
        ),
    ]
