# Generated by Django 5.2.11 on 2026-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0018_booking_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingemailtemplate',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Override hotel accent color for this email. Empty = use hotel default.', max_length=7),
        ),
        migrations.AddField(
            model_name='bookingemailtemplate',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Override hotel primary color for this email. Empty = use hotel default.', max_length=7),
        ),
    ]
