# Generated by Django 5.2.11 on 2026-02-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0019_booking_email_colors'),
        ('guides', '0005_add_mood_card_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Linked fieldguide destination for Explore tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='guides.destination'),
        ),
    ]
