# Generated by Django 5.2.11 on 2026-02-23 14:39

import concierge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0020_add_destination_fk_to_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingemailtemplate',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Override hotel accent color for this email. Empty = use hotel default.', max_length=7, validators=[concierge.models._hex_color_validator]),
        ),
        migrations.AlterField(
            model_name='bookingemailtemplate',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Override hotel primary color for this email. Empty = use hotel default.', max_length=7, validators=[concierge.models._hex_color_validator]),
        ),
    ]
