# Generated by Django 5.2.11 on 2026-02-23 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0021_booking_email_color_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email')], max_length=20)),
                ('target', models.CharField(help_text='Phone (E.164) or email. Auto-filled from member if linked, or manually entered for external contacts.', max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_routes', to='concierge.department')),
                ('experience', models.ForeignKey(blank=True, help_text='If set, route only fires for this experience. If null, fires for all requests in the department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_routes', to='concierge.experience')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_routes', to='concierge.hotel')),
                ('member', models.ForeignKey(blank=True, help_text='Link to an existing team member. When set, target is auto-derived from member contact info.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_routes', to='concierge.hotelmembership')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email')], max_length=20)),
                ('target', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('message_type', models.CharField(choices=[('TEMPLATE', 'Template'), ('SESSION', 'Session')], default='TEMPLATE', help_text='TEMPLATE = paid utility template, SESSION = free session message', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, help_text="'{event_type}:{public_id}:{escalation_tier}:{route_id}' — prevents duplicate sends on retries.", max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When recipient tapped a quick-reply button (ack/esc_ack/view).', null=True)),
                ('hotel', models.ForeignKey(help_text='Denormalized for efficient per-hotel log queries without joining through nullable route.', on_delete=django.db.models.deletion.CASCADE, to='concierge.hotel')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge.servicerequest')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.notificationroute')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppServiceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Digits-only E.164 without +', max_length=20)),
                ('last_inbound_at', models.DateTimeField(help_text='When we last received an inbound message from this phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_service_windows', to='concierge.hotel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.UniqueConstraint(condition=models.Q(('experience__isnull', False)), fields=('department', 'experience', 'channel', 'target'), name='unique_route_with_experience'),
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.UniqueConstraint(condition=models.Q(('experience__isnull', True)), fields=('department', 'channel', 'target'), name='unique_route_dept_wide'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['channel', 'status', '-created_at'], name='concierge_d_channel_734172_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(condition=models.Q(('provider_message_id__gt', '')), fields=['channel', 'provider_message_id'], name='idx_dlvr_chan_provmsg'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['hotel', '-created_at'], name='idx_dlvr_hotel_created'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['hotel', 'channel', 'status', '-created_at'], name='idx_dlvr_hotel_filtered'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(condition=models.Q(('acknowledged_at__isnull', True)), fields=['channel', 'target', 'request'], name='idx_dlvr_ack_lookup'),
        ),
        migrations.AddConstraint(
            model_name='deliveryrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id__gt', '')), fields=('channel', 'provider_message_id'), name='uniq_chan_provider_msg'),
        ),
        migrations.AddIndex(
            model_name='whatsappservicewindow',
            index=models.Index(fields=['phone', 'last_inbound_at'], name='concierge_w_phone_e277bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappservicewindow',
            unique_together={('hotel', 'phone')},
        ),
    ]
