# Generated by Django 5.2.11 on 2026-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0022_notification_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='escalation_fallback_channel',
            field=models.CharField(choices=[('NONE', 'None'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('EMAIL_WHATSAPP', 'Email + WhatsApp')], default='NONE', max_length=14),
        ),
    ]
