# Generated by Django 5.2.11 on 2026-02-24 09:38

from django.db import migrations, models
from django.core.files.storage import default_storage


def clear_image_icon_paths_and_files(apps, schema_editor):
    """Clear old image file paths and delete orphaned files from storage."""
    Department = apps.get_model('concierge', 'Department')
    depts_with_icons = Department.objects.exclude(icon='')
    count = 0
    for dept in depts_with_icons:
        # Delete the actual file from storage
        if dept.icon:
            try:
                if default_storage.exists(dept.icon):
                    default_storage.delete(dept.icon)
            except Exception:
                pass  # Best-effort cleanup
        dept.icon = ''
        dept.save(update_fields=['icon'])
        count += 1
    if count:
        print(f'  Cleared {count} department icon image path(s) and files')


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0023_replace_sms_with_whatsapp_escalation_channel'),
    ]

    operations = [
        # Clean data BEFORE narrowing the column (old paths could exceed 50 chars)
        migrations.RunPython(clear_image_icon_paths_and_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
