# Generated by Django 5.2.11 on 2026-02-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0027_event_notification_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scans', to='concierge.qrcode')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'qr_code'], name='concierge_q_date_bdd88a_idx')],
                'unique_together': {('qr_code', 'date')},
            },
        ),
    ]
