# Generated by Django 5.2.11 on 2026-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0029_team_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmembership',
            name='last_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
