# Generated by Django 5.2.11 on 2026-02-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0030_last_invite_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRequestOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UTILITARIAN', 'Utilitarian'), ('PERSONALIZATION', 'Personalization')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, upload_to='special_requests/')),
                ('cover_image', models.ImageField(blank=True, upload_to='special_requests/covers/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_display', models.CharField(blank=True, default='', max_length=100)),
                ('is_complimentary', models.BooleanField(default=False)),
                ('requires_room_number', models.BooleanField(default=False)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialRequestOfferingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='special_requests/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='notificationroute',
            name='unique_route_dept_wide',
        ),
        migrations.RemoveConstraint(
            model_name='notificationroute',
            name='route_scope_dept_xor_event',
        ),
        migrations.RemoveConstraint(
            model_name='notificationroute',
            name='route_no_experience_on_event_scope',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='special_request_category',
            field=models.CharField(blank=True, choices=[('UTILITARIAN', 'Utilitarian'), ('PERSONALIZATION', 'Personalization')], default='', help_text='Persisted from offering on SPECIAL_REQUEST, from guest on CUSTOM. Empty for BOOKING/INQUIRY.', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('INQUIRY', 'Inquiry'), ('CUSTOM', 'Custom'), ('SPECIAL_REQUEST', 'Special Request')], max_length=20),
        ),
        migrations.AddField(
            model_name='specialrequestoffering',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_request_offerings', to='concierge.department'),
        ),
        migrations.AddField(
            model_name='specialrequestoffering',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_request_offerings', to='concierge.hotel'),
        ),
        migrations.AddField(
            model_name='notificationroute',
            name='special_request_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_routes', to='concierge.specialrequestoffering'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='special_request_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='concierge.specialrequestoffering'),
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', True), ('experience__isnull', True), ('special_request_offering__isnull', True)), fields=('department', 'channel', 'target'), name='unique_route_dept_wide'),
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.UniqueConstraint(condition=models.Q(('special_request_offering__isnull', False)), fields=('special_request_offering', 'channel', 'target'), name='unique_offering_channel_target'),
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('event__isnull', True), ('special_request_offering__isnull', True)), models.Q(('department__isnull', True), ('event__isnull', False), ('special_request_offering__isnull', True)), models.Q(('department__isnull', True), ('event__isnull', True), ('special_request_offering__isnull', False)), _connector='OR'), name='route_scope_dept_xor_event_xor_offering'),
        ),
        migrations.AddConstraint(
            model_name='notificationroute',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', False), ('experience__isnull', True), _connector='OR'), name='route_experience_only_on_dept_scope'),
        ),
        migrations.AddField(
            model_name='specialrequestofferingimage',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='concierge.specialrequestoffering'),
        ),
        migrations.AlterUniqueTogether(
            name='specialrequestoffering',
            unique_together={('hotel', 'slug')},
        ),
    ]
