# Generated by Django 5.2.11 on 2026-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0031_specialrequestoffering_specialrequestofferingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='custom_requests_enabled',
            field=models.BooleanField(default=False, help_text='Allow guests to submit freeform custom requests'),
        ),
    ]
