# Generated by Django 5.2.11 on 2026-02-27 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0032_add_custom_requests_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('GUEST_INVITE', 'Guest Invite')], max_length=30)),
                ('gupshup_template_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('body_text', models.TextField()),
                ('footer_text', models.CharField(default='Powered by Refuje', max_length=60)),
                ('buttons', models.JSONField(default=list)),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wa_templates', to='concierge.hotel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('hotel__isnull', False), ('is_active', True)), fields=('hotel', 'template_type'), name='unique_active_template_per_hotel_type'), models.UniqueConstraint(condition=models.Q(('hotel__isnull', True), ('is_active', True)), fields=('template_type',), name='unique_active_global_template_per_type')],
            },
        ),
    ]
