# Generated by Django 5.2.11 on 2026-02-27 05:31

from django.db import migrations


def seed_guest_invite_template(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('concierge', 'WhatsAppTemplate')
    WhatsAppTemplate.objects.get_or_create(
        hotel=None,
        template_type='GUEST_INVITE',
        defaults={
            'gupshup_template_id': '',  # filled after Meta approval
            'name': 'Guest Invite - Default',
            'body_text': (
                'Hi {{2}}, {{1}} has invited you to explore their digital concierge. '
                'Browse activities, experiences, events & more \u2014 or make a special request. '
                'Tap below to get started.'
            ),
            'footer_text': 'Powered by Refuje',
            'buttons': [
                {'type': 'quick_reply', 'label': 'Access Concierge'},
                {'type': 'quick_reply', 'label': 'Enable WhatsApp Updates'},
            ],
            'variables': [
                {'index': 1, 'key': 'hotel_name', 'label': 'Hotel name'},
                {'index': 2, 'key': 'guest_name', 'label': 'Guest name'},
            ],
        },
    )


def reverse_seed(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('concierge', 'WhatsAppTemplate')
    WhatsAppTemplate.objects.filter(
        hotel=None, template_type='GUEST_INVITE', name='Guest Invite - Default',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0033_add_whatsapp_template'),
    ]

    operations = [
        migrations.RunPython(seed_guest_invite_template, reverse_seed),
    ]
