# Generated by Django 5.2.11 on 2026-02-27 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0034_seed_guest_invite_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='guest_invite_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('guest_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.gueststay')),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_invites', to='concierge.hotel')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='guest_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='concierge.guestinvite'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['hotel', '-created_at'], name='concierge_g_hotel_i_9265c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('hotel', 'guest_phone'), name='unique_active_invite_per_phone_hotel'),
        ),
    ]
