# Generated by Django 5.2.11 on 2026-02-27 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0035_add_guest_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='external_review_threshold',
            field=models.PositiveSmallIntegerField(default=4, help_text='Minimum score (4 or 5) to show external review prompt'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='external_review_url',
            field=models.URLField(blank=True, help_text='Google/TripAdvisor link shown to guests who rate 4-5'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating_batch_hour',
            field=models.PositiveSmallIntegerField(default=20, help_text='Hour of day (0-23) in hotel timezone to send batch'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating_delay_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Hours after CONFIRMED before rating prompt is queued'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating_max_per_batch',
            field=models.PositiveSmallIntegerField(default=3, help_text='Max request prompts per batch WhatsApp message'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ratings_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rating_prompt_eligible_at',
            field=models.DateTimeField(blank=True, help_text='Set to confirmed_at + delay when CONFIRMED and ratings enabled. Used by queue task.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('ESCALATION', 'Escalation'), ('DAILY_DIGEST', 'Daily Digest'), ('SYSTEM', 'System'), ('LOW_RATING_ALERT', 'Low Rating Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requestactivity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('VIEWED', 'Viewed'), ('ACKNOWLEDGED', 'Acknowledged'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('NOTE_ADDED', 'Note Added'), ('OWNERSHIP_TAKEN', 'Ownership Taken'), ('EXPIRED', 'Expired'), ('REASSIGNED', 'Reassigned'), ('RATING_SUBMITTED', 'Rating Submitted'), ('FEEDBACK_ALERT', 'Feedback Alert')], max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('REQUEST', 'Request'), ('STAY', 'Stay')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('review_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('guest_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='concierge.gueststay')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='concierge.hotel')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='concierge.servicerequest')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'created_at'], name='concierge_r_hotel_i_62be24_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='rating_score_range'), models.UniqueConstraint(condition=models.Q(('service_request__isnull', False)), fields=('service_request',), name='unique_rating_per_request'), models.UniqueConstraint(condition=models.Q(('rating_type', 'STAY')), fields=('guest_stay',), name='unique_stay_rating_per_stay'), models.CheckConstraint(condition=models.Q(models.Q(('guest_stay__isnull', True), ('rating_type', 'REQUEST'), ('service_request__isnull', False)), models.Q(('guest_stay__isnull', False), ('rating_type', 'STAY'), ('service_request__isnull', True)), _connector='OR'), name='rating_type_xor_fk')],
            },
        ),
        migrations.CreateModel(
            name='RatingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('REQUEST', 'Request'), ('STAY', 'Stay')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('eligible_at', models.DateTimeField()),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_key', models.CharField(blank=True, max_length=40, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_prompts', to=settings.AUTH_USER_MODEL)),
                ('guest_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_prompts', to='concierge.gueststay')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_prompts', to='concierge.hotel')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_prompts', to='concierge.servicerequest')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'status', 'prompt_type', 'eligible_at'], name='rp_batch_query_idx'), models.Index(fields=['hotel', 'batch_key', 'guest'], name='rp_dedup_idx'), models.Index(fields=['hotel', 'guest', 'status'], name='rp_guest_read_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('service_request__isnull', False)), fields=('service_request',), name='unique_prompt_per_request'), models.UniqueConstraint(condition=models.Q(('prompt_type', 'STAY')), fields=('guest_stay',), name='unique_stay_prompt_per_stay'), models.CheckConstraint(condition=models.Q(models.Q(('guest_stay__isnull', True), ('prompt_type', 'REQUEST'), ('service_request__isnull', False)), models.Q(('guest_stay__isnull', False), ('prompt_type', 'STAY'), ('service_request__isnull', True)), _connector='OR'), name='prompt_type_xor_fk')],
            },
        ),
    ]
