# Generated by Django 5.2.11 on 2026-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0036_guest_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='template_type',
            field=models.CharField(choices=[('GUEST_INVITE', 'Guest Invite'), ('GUEST_RATING_BATCH', 'Guest Rating Batch'), ('GUEST_STAY_SURVEY', 'Guest Stay Survey'), ('LOW_SCORE_ALERT', 'Low Score Alert')], max_length=30),
        ),
    ]
