# Generated by Django 5.2.11

from django.db import migrations


def seed_templates(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('concierge', 'WhatsAppTemplate')

    # 1. Update existing GUEST_INVITE — fix gupshup_template_id and variable order
    WhatsAppTemplate.objects.filter(
        hotel=None, template_type='GUEST_INVITE', is_active=True,
    ).update(
        gupshup_template_id='533d4fe6-b1f5-4937-9ed2-db7b6b89504b',
        body_text=(
            'Hi {{1}}, {{2}} has invited you to explore their digital concierge. '
            'Browse activities, experiences, events & more \u2014 or make a special request. '
            'Tap below to get started.'
        ),
        variables=[
            {'index': 1, 'key': 'guest_name', 'label': 'Guest name'},
            {'index': 2, 'key': 'hotel_name', 'label': 'Hotel name'},
        ],
    )

    # 2. GUEST_RATING_BATCH
    WhatsAppTemplate.objects.get_or_create(
        hotel=None,
        template_type='GUEST_RATING_BATCH',
        is_active=True,
        defaults={
            'gupshup_template_id': '8fdd86e7-8054-4b7e-816d-2d3e68d3509b',
            'name': 'Guest Rating Batch - Default',
            'body_text': (
                'Hi {{1}}, thank you for staying at {{2}}! '
                'We\u2019d love your feedback on {{3}} experience(s). '
                'Tap below to rate.'
            ),
            'footer_text': 'Powered by Refuje',
            'buttons': [
                {'type': 'url', 'label': 'Rate Now'},
            ],
            'variables': [
                {'index': 1, 'key': 'guest_name', 'label': 'Guest name'},
                {'index': 2, 'key': 'hotel_name', 'label': 'Hotel name'},
                {'index': 3, 'key': 'experience_count', 'label': 'Experience count'},
                {'index': 4, 'key': 'rate_url_suffix', 'label': 'Rate URL suffix'},
            ],
        },
    )

    # 3. GUEST_STAY_SURVEY
    WhatsAppTemplate.objects.get_or_create(
        hotel=None,
        template_type='GUEST_STAY_SURVEY',
        is_active=True,
        defaults={
            'gupshup_template_id': 'd6c92ea7-0ad8-4611-b841-c47a92db6c94',
            'name': 'Guest Stay Survey - Default',
            'body_text': (
                'Hi {{1}}, thank you for choosing {{2}}! '
                'We\u2019d love to hear about your overall experience. '
                'Tap below to share your feedback.'
            ),
            'footer_text': 'Powered by Refuje',
            'buttons': [
                {'type': 'url', 'label': 'Share Feedback'},
            ],
            'variables': [
                {'index': 1, 'key': 'guest_name', 'label': 'Guest name'},
                {'index': 2, 'key': 'hotel_name', 'label': 'Hotel name'},
                {'index': 3, 'key': 'rate_url_suffix', 'label': 'Rate URL suffix'},
            ],
        },
    )

    # 4. LOW_SCORE_ALERT
    WhatsAppTemplate.objects.get_or_create(
        hotel=None,
        template_type='LOW_SCORE_ALERT',
        is_active=True,
        defaults={
            'gupshup_template_id': 'cd24a1c3-12c8-487d-9d5c-1fb02e1fd958',
            'name': 'Low Score Alert - Default',
            'body_text': (
                'Rating: {{2}}\n\n'
                'Feedback: "{{3}}"\n\n'
                'This is an automated alert from your hotel\'s guest feedback system.\n\n'
                'Please review and follow up with the guest at your earliest '
                'convenience to address their concerns.'
            ),
            'footer_text': 'Powered by Refuje',
            'buttons': [
                {'type': 'url', 'label': 'View Dashboard'},
            ],
            'variables': [
                {'index': 1, 'key': 'guest_summary', 'label': 'Guest summary'},
                {'index': 2, 'key': 'rating_detail', 'label': 'Rating detail'},
                {'index': 3, 'key': 'feedback_preview', 'label': 'Feedback preview'},
                {'index': 4, 'key': 'dashboard_path', 'label': 'Dashboard URL path'},
            ],
        },
    )


def reverse_seed(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('concierge', 'WhatsAppTemplate')
    WhatsAppTemplate.objects.filter(
        hotel=None,
        template_type__in=[
            'GUEST_RATING_BATCH', 'GUEST_STAY_SURVEY', 'LOW_SCORE_ALERT',
        ],
    ).delete()
    # Revert GUEST_INVITE to original seed values
    WhatsAppTemplate.objects.filter(
        hotel=None, template_type='GUEST_INVITE', is_active=True,
    ).update(
        gupshup_template_id='',
        body_text=(
            'Hi {{2}}, {{1}} has invited you to explore their digital concierge. '
            'Browse activities, experiences, events & more \u2014 or make a special request. '
            'Tap below to get started.'
        ),
        variables=[
            {'index': 1, 'key': 'hotel_name', 'label': 'Hotel name'},
            {'index': 2, 'key': 'guest_name', 'label': 'Guest name'},
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0037_extend_wa_template_types'),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_seed),
    ]
