# Generated by Django 5.2.11 on 2026-03-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0038_seed_wa_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=10),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'created_at'], name='concierge_o_email_9752dc_idx'),
        ),
    ]
