# Generated by Django 5.2.11 on 2026-03-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0039_otpcode_email_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_room_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='requires_room_number',
            field=models.BooleanField(default=True),
        ),
    ]
